In [1]:
import numpy as np


In [2]:
# Create a 2D array (5 samples × 4 features) with random integers between 10 and 100
arr = np.random.randint(10, 100, size=(5, 4))
print("Original Array:\n", arr)


Original Array:
 [[85 36 16 22]
 [18 54 11 12]
 [52 83 81 51]
 [80 34 14 91]
 [54 41 14 77]]


In [3]:
# Step 1: Calculate mean of each column
mean = arr.mean(axis=0)
print("\nMean of each column:\n", mean)

# Step 2: Calculate standard deviation of each column
std = arr.std(axis=0)
print("\nStandard deviation of each column:\n", std)

# Step 3: Normalize (subtract mean, divide by std)
normalized_arr = (arr - mean) / std
print("\nNormalized Array:\n", normalized_arr)



Mean of each column:
 [57.8 49.6 27.2 50.6]

Standard deviation of each column:
 [23.93658288 18.09530326 26.94735609 30.45389959]

Normalized Array:
 [[ 1.13633596 -0.75157624 -0.41562519 -0.93912439]
 [-1.66272689  0.24315702 -0.60117215 -1.26748957]
 [-0.24230693  1.84578283  1.99648529  0.01313461]
 [ 0.92745068 -0.86210216 -0.48984397  1.3265953 ]
 [-0.15875282 -0.47526145 -0.48984397  0.86688406]]


In [4]:
# After normalization, each column should have mean ≈ 0 and std ≈ 1
print("Mean after normalization:", normalized_arr.mean(axis=0))
print("Std after normalization:", normalized_arr.std(axis=0))


Mean after normalization: [ 1.33226763e-16 -7.77156117e-17  4.44089210e-17 -8.88178420e-17]
Std after normalization: [1. 1. 1. 1.]
