In [1]:
import numpy as np

# Create a 2D array (5 rows × 4 columns) with random integers between 10 and 100
arr = np.random.randint(10, 100, size=(5, 4))

print("Original Array:\n", arr)


Original Array:
 [[91 64 73 99]
 [75 68 28 55]
 [16 73 99 78]
 [45 12 43 60]
 [74 52 58 60]]


In [2]:
# Calculate the mean for each column
col_mean = arr.mean(axis=0)

print("Mean of each column:", col_mean)


Mean of each column: [60.2 53.8 60.2 70.4]


In [3]:
# Find the maximum value in each row
row_max = arr.max(axis=1)

print("Maximum value in each row:", row_max)


Maximum value in each row: [99 75 99 60 74]


In [4]:
# Calculate the total sum of all elements in the array
total_sum = arr.sum()

print("Total sum of all elements:", total_sum)


Total sum of all elements: 1223


In [5]:
# Select the first two rows and last two columns
subset = arr[0:2, 2:4]
print("First two rows and last two columns:\n", subset)

# Use boolean indexing to find elements greater than 50
greater_than_50 = arr[arr > 50]
print("\nElements greater than 50:", greater_than_50)


First two rows and last two columns:
 [[73 99]
 [28 55]]

Elements greater than 50: [91 64 73 99 75 68 55 73 99 78 60 74 52 58 60]


In [6]:
print("Original Array:\n", arr)
print("\nColumn Means:", col_mean)
print("Row Maximums:", row_max)
print("Total Sum:", total_sum)
print("\nSubset (First 2 rows, Last 2 columns):\n", subset)
print("\nElements greater than 50:", greater_than_50)


Original Array:
 [[91 64 73 99]
 [75 68 28 55]
 [16 73 99 78]
 [45 12 43 60]
 [74 52 58 60]]

Column Means: [60.2 53.8 60.2 70.4]
Row Maximums: [99 75 99 60 74]
Total Sum: 1223

Subset (First 2 rows, Last 2 columns):
 [[73 99]
 [28 55]]

Elements greater than 50: [91 64 73 99 75 68 55 73 99 78 60 74 52 58 60]
