In [1]:
import numpy as np


In [2]:
# Example dataset: 5 samples, 3 features
X = np.array([[1, 200, 3],
              [2, 210, 6],
              [3, 190, 9],
              [4, 220, 12],
              [5, 205, 15]])

print("Original Dataset:\n", X)


Original Dataset:
 [[  1 200   3]
 [  2 210   6]
 [  3 190   9]
 [  4 220  12]
 [  5 205  15]]


In [3]:
# Compute mean and standard deviation for each column
mean_X = X.mean(axis=0)
std_X = X.std(axis=0)

# Standardize dataset
X_standardized = (X - mean_X) / std_X

print("\nStandardized Dataset:\n", X_standardized)



Standardized Dataset:
 [[-1.41421356 -0.5        -1.41421356]
 [-0.70710678  0.5        -0.70710678]
 [ 0.         -1.5         0.        ]
 [ 0.70710678  1.5         0.70710678]
 [ 1.41421356  0.          1.41421356]]


In [4]:
print("\nColumn-wise Mean after Standardization:\n", X_standardized.mean(axis=0))
print("Column-wise Std after Standardization:\n", X_standardized.std(axis=0))



Column-wise Mean after Standardization:
 [ 0.0000000e+00  0.0000000e+00 -4.4408921e-17]
Column-wise Std after Standardization:
 [1. 1. 1.]
